### ISSUE TITLE
黑苹果无法打开扩展

### ISSUE THREAD

**Issue by ghost** [guohongwei719/GHWXcodeExtension#5]
黑苹果上，按照你文档中的操作，在双击打开GHWXcodeExtension的时候 GHWXcodeExtension 会立刻退出，请问这个问题可以处理吗？

**Comment by guohongwei719** [comment]
兄弟，本来就是一闪而过的，这是正常现象，按照流程操作应该可以的哦，去Xcode的菜单 Editor 下面看看有没有。

**Comment by ghost** [comment]
设置>扩展 中没有显示，无法进行勾选；Xcode 菜单 Editor 下面也没有

![image](https://user-images.githubusercontent.com/14041988/65115786-c3c54100-da1a-11e9-9e2d-776ef1b8a28d.png)

扩展这里没有展示 xcode source editor

**Comment by guohongwei719** [comment]
你系统版本多少，最低支持 10.13

**Comment by ghost** [comment]
10.13.6 (17G65)

**Comment by guohongwei719** [comment]
你按照最后的调试方式看看，看看能不能用起来。

**Comment by ghost** [comment]
按照调试步骤操作：运行》打开新项目 》editor 下没有显示插件。

我自己的 MacBook 使用你提供的压缩包是可以正常使用的，现在这台电脑是黑苹果，不知道是否有关系。

**Comment by guohongwei719** [comment]
有可能有关系，那你可以根据源码自己生成一个试试，看能否可用。

**Comment by ghost** [comment]
已经找到处理方法了，不是黑苹果的问题：
Xcode source Editor 没有显示问题处理
https://www.jianshu.com/p/c554de4a86ea
