### ISSUE TITLE
这个插件无法使用了好像

### ISSUE THREAD

**Issue by WangGuibin** [guohongwei719/GHWXcodeExtension#8]
![image](https://user-images.githubusercontent.com/15259130/69408569-d40adc80-0d39-11ea-94ea-7c3579e74bcd.png)

```
sudo spctl --master-disable
```
允许任何来源也一样
我尝试自己编译但是控制台提示以下内容，Xcode停止了运行
```
No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting
```

**Comment by Leo617** [comment]
搞定了么，我也发现这个问题了。

**Comment by WangGuibin** [comment]
> 搞定了么，我也发现这个问题了。

并没有，鄙人水平有限，坐等大佬们搞定，暂时就用代码块顶一顶了😅

**Comment by guohongwei719** [comment]
下载下来提示有问题这个就不好说，我暂时没遇到过。不过你自己在本地变化应该是可以的，你别管控制台提示什么，去看看Products目录下是否有生成GHWXcodeExtension.app，按照流程来操作应该就行了吧。再不行就多试几次吧，比如换个浏览器下载试试，重启Xcode或电脑看看。

**Comment by WangGuibin** [comment]
> 下载下来提示有问题这个就不好说，我暂时没遇到过。不过你自己在本地变化应该是可以的，你别管控制台提示什么，去看看Products目录下是否有生成GHWXcodeExtension.app，按照流程来操作应该就行了吧。再不行就多试几次吧，比如换个浏览器下载试试，重启Xcode或电脑看看。

按你说的编译Products取出来，已解决问题
